language: rust
env:
  global:
    - PROJECT_NAME: imdb-rename
    - RUST_BACKTRACE: full
addons:
  apt:
    packages:
      - musl-tools
matrix:
  fast_finish: true
  include:
    # Nightly channel.
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    # Beta channel. We enable these to make sure there are no regressions in
    # Rust beta releases.
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    # Minimum Rust supported channel. We enable these to make sure imdb-rename
    # continues to work on the advertised minimum Rust version.
    - os: linux
      rust: 1.22.1
      env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  file_glob: true
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    branch: master
    tags: true
  api_key:
    secure: "XBUgASwSdXY50efuo6x6pQTBo1J2EAdziRKgaazmaqqQPbX0Ux+Sang8MmoFMDAYfsjV2xdRrrDfJ+XuUUIpvtCic7/9XhtemKM4FLwAwPPtcdwnj1iQbZxKPlShBbzW5QUKmQk+TK4u/iYXFv4cM4WtdJR/fL3fZiHk7qs+0o8DAwNXKx0NbhLuBDR0HhylTyF0qa59tpdu+JfK/kk3xgNee3vrt4kh4xiEG47Gdry7WntSG6r/1I8yJsOs/xGQrTwMcsieIP/O/4AduTZHSOokesGogYCS7EGqz5fPD9oogtl1htS8xYO2OxdTh9xLogEgoOyCXIwPvuOGH2W6x6p1wS+DusnXCVuTsZJ0YLMy4Fbr8TYoQLwI4PIVPZY0Gzvi/SD9qbR3NY8X+NHAsSKHi5VuFnvD9o6b7euIwHs+t2Yi2UMPXyOZ12PhS52cvDesdhAJtcw0Lzn4WPJAY6+7f1/NskHUS2VcXKPRxZMzpte7TB1W6JzIOm15dk8A8u5/ubdhGWfOBZXZhJeQ3mBKtXZJb05pAxdv1S7XHZNWoVA6jGZqNIFDM1ecbqXTdQsjYUgQAAjbahx5ClSL3lh1mZLYy+NxwrAfsuY1NRoJ11oxZgSthQrDs3uAibaV26YvLHpX1k+YH0rAZHYfJVoeucopMF5HwtRrVUZ/dqw="
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed.
    - /^\d+\.\d+\.\d+.*$/
notifications:
  email:
    on_success: never
